import { expect, test } from "@playwright/test";

test("real stack: login, upload, processing, correction, hypothesis and evidence ZIP", async ({ page }) => {
  await page.goto("/login");
  await page.getByLabel("Email").fill(process.env.FIRST_USER_EMAIL ?? "owner@local.test");
  await page.getByLabel("Password").fill(process.env.FIRST_USER_PASSWORD ?? "change-this-password");
  await page.getByRole("button", { name: "Sign in" }).click();
  await page.waitForURL("**/dashboard");
  await page.goto("/inbox");
  const sample = Buffer.alloc(44 + 16_000 * 2);
  sample.write("RIFF", 0);
  sample.writeUInt32LE(sample.length - 8, 4);
  sample.write("WAVEfmt ", 8);
  sample.writeUInt32LE(16, 16);
  sample.writeUInt16LE(1, 20);
  sample.writeUInt16LE(1, 22);
  sample.writeUInt32LE(16_000, 24);
  sample.writeUInt32LE(32_000, 28);
  sample.writeUInt16LE(2, 32);
  sample.writeUInt16LE(16, 34);
  sample.write("data", 36);
  sample.writeUInt32LE(sample.length - 44, 40);
  await page.locator('select[name="item_type"]').selectOption("audio");
  await page.locator('input[name="file"]').setInputFiles({ name: "e2e.wav", mimeType: "audio/wav", buffer: sample });
  await page.locator('input[name="frequency_hz"]').fill("4625000");
  await page.getByRole("button", { name: "Save" }).click();
  await expect(page.getByRole("status")).toContainText("processing queued");
  const apiBase = process.env.E2E_API_URL ?? "http://localhost:8000/api/v1";
  const csrf = (await page.context().cookies()).find(cookie => cookie.name === "signal_csrf");
  expect(csrf).toBeTruthy();
  let sessionId = "";
  await expect.poll(async () => {
    const response = await page.request.post(`${apiBase}/search/sessions`, { headers: { "x-csrf-token": csrf!.value }, data: { frequency_min_hz: 4_625_000, frequency_max_hz: 4_625_000, limit: 10 } });
    if (!response.ok()) return 0;
    const body = await response.json();
    sessionId = body.data[0]?.id ?? "";
    return body.data.length;
  }, { timeout: 300_000, intervals: [2_000, 5_000] }).toBeGreaterThan(0);
  const detail = await page.request.get(`${apiBase}/sessions/${sessionId}`);
  expect(detail.ok()).toBeTruthy();
  const session = (await detail.json()).data;
  expect(session.segment_ids.length).toBeGreaterThan(0);
  const correction = await page.request.post(`${apiBase}/segments/${session.segment_ids[0]}/transcripts`, { headers: { "x-csrf-token": csrf!.value }, data: { text: "E2E corrected transcript", language: "en", mark_preferred: true } });
  expect(correction.ok()).toBeTruthy();
  const refreshed = await page.request.get(`${apiBase}/segments/${session.segment_ids[0]}`);
  const transcripts = (await refreshed.json()).data.transcripts;
  expect(transcripts.some((row: { transcript_type: string }) => row.transcript_type === "MACHINE")).toBeTruthy();
  expect(transcripts.some((row: { transcript_type: string; is_preferred: boolean }) => row.transcript_type === "MANUAL_CORRECTED" && row.is_preferred)).toBeTruthy();
  const hypothesis = await page.request.post(`${apiBase}/hypotheses`, { headers: { "x-csrf-token": csrf!.value }, data: { title: "E2E evidence hypothesis", statement: "This is an end-to-end test hypothesis.", related_session_ids: [sessionId], created_by: "USER" } });
  expect(hypothesis.ok()).toBeTruthy();
  const evidence = await page.request.get(`${apiBase}/export/evidence-bundle?session_id=${sessionId}`);
  expect(evidence.ok()).toBeTruthy();
  expect((await evidence.body()).subarray(0, 2).toString()).toBe("PK");
});
